# Generated by Django 2.1 on 2018-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_blog_app', '0002_auto_20180827_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
