# Generated by Django 2.1 on 2018-08-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_blog_app', '0003_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
